server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service
  profiles:
    active: ${ENVIRONMENT:docker}

grpc:
  server:
    port: ${AUTH_SERVICE_GRPC_SERVER_PORT:9091}
    address: 0.0.0.0
    max-inbound-message-size: 10485760
    keepalive-time: 300s
    keepalive-timeout: 30s
    permit-keepalive-time: 300s

  client:
    user-service:
      address: static://${USER_SERVICE_GRPC_HOST:user-service}:${USER_SERVICE_GRPC_PORT:9092}
      negotiationType: plaintext
      
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.tickey.authservice: ${LOGGING_LEVEL_COM_TICKEY:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}