services:
  mongo:
    image: mongo:6
    container_name: mongo
    env_file: ./user-service/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15-alpine
    env_file: ./ticket-service/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    env_file: ./user-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  ticket-service:
    build: 
      context: ./ticket-service
      dockerfile: Dockerfile
    env_file: ./ticket-service/.env
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  gateway-service:
    build: 
      context: ./gateway-service
      dockerfile: Dockerfile
    env_file: ./gateway-service/.env
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - ticket-service
      - auth-service

  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    env_file: ./auth-service/.env
    ports:
      - "8081:8081"

volumes:
  mongo_data:
  pgdata: