server:
  port: ${GATEWAY_SERVICE_PORT:8080}

spring:
  application:
    name: gateway-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

grpc:
  server:
    port: -1
  client:
    auth-service:
      address: static://${AUTH_SERVICE_GRPC_HOST}:${AUTH_SERVICE_GRPC_PORT}
      negotiationType: plaintext

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
