server:
  port: ${GATEWAY_SERVICE_PORT:8080}

spring:
  application:
    name: gateway-service
  profiles:
    active: ${ENVIRONMENT:docker}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}

grpc:
  client:
    auth-service:
      address: static://${AUTH_SERVICE_GRPC_HOST:auth-service}:${AUTH_SERVICE_GRPC_PORT:9091}
      negotiationType: plaintext

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.tickey.gatewayservice: ${LOGGING_LEVEL_COM_TICKEY:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
