server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: user-service
  profiles:
    active: ${ENVIRONMENT:docker}

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${USER_DB_NAME}
      username: ${MONGO_INITDB_ROOT_USERNAME:}
      password: ${MONGO_INITDB_ROOT_PASSWORD:}
      authentication-database: admin
      auto-index-creation: true

grpc:
  server:
    port: ${USER_SERVICE_GRPC_SERVER_PORT:9092}
    address: 0.0.0.0
    max-inbound-message-size: 10485760
    keepalive-time: 300s
    keepalive-timeout: 30s
    permit-keepalive-time: 300s

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.ticket.userservice: ${LOGGING_LEVEL_COM_TICKEY:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

